version: 2
references:
  executor: &executor
    machine:
      image: circleci/classic:201711-01

  attach_workspace: &attach_workspace
    attach_workspace:
      at: /tmp/workspace

  import_image: &import_image
    run: |
      docker load -i /tmp/workspace/image.tar

  import_final_image: &import_final_image
    run: |
      docker load -i /tmp/workspace/final_image.tar

jobs:
  build:
    <<: *executor
    steps:
     - checkout
     - run: |
         set -x
         export PULL_CACHE=yes
         source scripts/common.sh
         do_docker_build signalfx-agent-dev latest dev-extras
         ./scripts/build
     - run: |
         mkdir -p /tmp/workspace
         docker save -o /tmp/workspace/image.tar signalfx-agent-dev:latest
         docker save -o /tmp/workspace/final_image.tar quay.io/signalfx/signalfx-agent-dev:$(eval "./scripts/current_version")
     - persist_to_workspace:
         root: /tmp/workspace
         paths:
           - image.tar
           - final_image.tar

  lint: 
    <<: *executor
    steps:
      - *attach_workspace
      - *import_image
      - run: docker run --rm signalfx-agent-dev make lint

  vet: 
    <<: *executor
    steps:
      - *attach_workspace
      - *import_image
      - run: docker run --rm signalfx-agent-dev make vet

  gotests: 
    <<: *executor
    steps:
      - *attach_workspace
      - *import_image
      - run: |
          mkdir ~/testresults
          docker run --rm \
            -v ~/testresults:/output \
            signalfx-agent-dev \
            bash -eo pipefail -c "make templates && go test -v ./... | go2xunit > /output/unit.xml"

      - store_test_results:
          path: ~/testresults

  docs_test: 
    <<: *executor
    steps:
      - *attach_workspace
      - *import_image
      - checkout
      - run: |
          docker run --rm \
            -v $(eval "echo -n $CIRCLE_WORKING_DIRECTORY")/.git:/go/src/github.com/signalfx/signalfx-agent/.git \
            signalfx-agent-dev \
            bash -ec "make docs && git diff --exit-code" || \
            (echo 'Docs are not updated in the repo! Run `make docs` in the dev image and commit those changes.' && exit 1)

  integration_tests: 
    <<: *executor
    steps:
      - *attach_workspace
      - *import_image
      - *import_final_image
      - run: |
          mkdir ~/testresults
          docker run -d -p 5000:5000 --restart always --name registry registry
          docker images
          docker tag quay.io/signalfx/signalfx-agent-dev:$(eval "./scripts/current_version") localhost:5000/signalfx-agent-dev:latest
          docker push localhost:5000/signalfx-agent-dev
          docker run --rm --net host -v /var/run/docker.sock:/var/run/docker.sock -v ~/testresults:/output signalfx-agent-dev pytest -n8 --junitxml=/output/integration_tests.xml -m "not packaging and not installer" --k8s_version=all tests

      - store_test_results:
          path: ~/testresults

  rpm_package_tests:
    <<: *executor
    steps:
      - checkout
      - run: |
          mkdir ~/testresults

          if ! scripts/changes-include-dir packaging/rpm; then
              echo "RPM packaging code has not changed, skipping tests!"
              exit 0
          fi

          sudo apt-get update && sudo apt-get install -y python3-pip
          sudo pip3 install -r tests/requirements.txt

          export PULL_CACHE=yes
          ./packaging/rpm/build

          mkdir /tmp/scratch

          pytest -n auto -m "rpm" --junitxml=~/testresults/rpm.xml ./tests/packaging

      - store_test_results:
          path: ~/testresults

      - store_artifacts:
          path: ~/project/packaging/rpm/output
          destination: /packages/

  deb_package_tests:
    <<: *executor
    steps:
      - checkout
      - run: |
          mkdir ~/testresults

          if ! scripts/changes-include-dir packaging/deb; then
              echo "Debian packaging code has not changed, skipping tests!"
              exit 0
          fi

          sudo apt-get update && sudo apt-get install -y python3-pip
          sudo pip3 install -r tests/requirements.txt

          export PULL_CACHE=yes
          ./packaging/deb/build

          mkdir /tmp/scratch

          pytest -n auto -m "deb" --junitxml=~/testresults/deb.xml ./tests/packaging

      - store_test_results:
          path: ~/testresults

      - store_artifacts:
          path: ~/project/packaging/deb/output
          destination: /packages/

  chef_tests:
    <<: *executor
    steps:
      - checkout
      - run: |
          mkdir ~/testresults

          if ! scripts/changes-include-dir deployments/chef; then
              echo "Chef cookbook code has not changed, skipping tests!"
              exit 0
          fi

          cd deployments/chef
          make dev-image
          docker run --rm \
            signalfx-agent-chef-dev \
            chef exec rspec --format RspecJunitFormatter > ~/testresults/chefspec.xml

          docker run --rm \
            signalfx-agent-chef-dev \
            foodcritic .

      - store_test_results:
          path: ~/testresults

  puppet_tests:
    <<: *executor
    steps:
      - checkout
      - run: |
          mkdir ~/testresults

          if ! scripts/changes-include-dir deployments/puppet; then
              echo "Puppet module code has not changed, skipping tests!"
              exit 0
          fi

          cd deployments/puppet
          make dev-image
          docker run --rm \
            signalfx-agent-puppet-dev \
            rspec spec --format RspecJunitFormatter > ~/testresults/puppetspec.xml

          docker run --rm \
            signalfx-agent-puppet-dev \
            puppet-lint .

      - store_test_results:
          path: ~/testresults
workflows:
  version: 2
  build_test:
    jobs:
     - build
     - lint:
        requires:
         - build
     - vet:
        requires:
         - build
     - gotests:
        requires:
         - build
     - integration_tests:
        requires:
         - build
     - docs_test:
        requires:
         - build
     - rpm_package_tests
     - deb_package_tests
     - chef_tests
     - puppet_tests
