version: 2
references:
  executor: &executor
    machine:
      image: circleci/classic:201711-01

  attach_workspace: &attach_workspace
    attach_workspace:
      at: /tmp/workspace

  import_image: &import_image
    run: |
      docker load -i /tmp/workspace/image.tar

  import_final_image: &import_final_image
    run: |
      docker load -i /tmp/workspace/final_image.tar

  import_minikube_image: &import_minikube_image
    run: |
      docker load -i /tmp/workspace/minikube_image.tar

  run_k8s_integration_tests: &run_k8s_integration_tests
    run:
      no_output_timeout: 30m
      command: |
        set -x
        set +e
        for ((i=0; i<3; i++)); do
            mkdir ~/testresults
            docker run -d --rm \
                -e K8S_VERSION=$(eval "echo -n $K8S_VERSION") \
                -p 8443 \
                -p 2375 \
                -v /tmp/scratch:/tmp/scratch \
                --privileged \
                --name minikube \
                minikube:latest
            if [ $? -eq 0 ]; then
                docker run --rm --net host \
                    -v /var/run/docker.sock:/var/run/docker.sock \
                    -v /tmp/scratch:/tmp/scratch \
                    -v ~/testresults:/output \
                    --name signalfx-agent-dev \
                    signalfx-agent-dev \
                        pytest \
                            -m "k8s" \
                            --verbose \
                            --junitxml=/output/integration_tests.xml \
                            --html=/output/k8s_integration_tests.html \
                            --self-contained-html \
                            --k8s-versions=$(eval "echo -n $K8S_VERSION") \
                            --k8s-timeout=600 \
                            --k8s-agent-name=quay.io/signalfx/signalfx-agent-dev \
                            --k8s-agent-tag=k8s-test \
                            --k8s-metrics-timeout=600 \
                            --k8s-container=minikube \
                            tests && exit 0
            fi
            docker rm -f minikube signalfx-agent-dev
            rm -rf ~/testresults
            sleep 10
        done
        exit 1

jobs:
  build:
    <<: *executor
    steps:
     - checkout
     - run: |
         set -x
         export PULL_CACHE=yes
         source scripts/common.sh
         do_docker_build signalfx-agent-dev latest dev-extras
     - run: |
         mkdir -p /tmp/workspace
         docker save -o /tmp/workspace/image.tar signalfx-agent-dev:latest
     - persist_to_workspace:
         root: /tmp/workspace
         paths:
           - image.tar

  build_final_image:
    <<: *executor
    steps:
     - checkout
     - run: |
         set -x
         export PULL_CACHE=yes
         export AGENT_VERSION=k8s-test
         ./scripts/build
     - run: |
         mkdir -p /tmp/workspace
         docker save -o /tmp/workspace/final_image.tar quay.io/signalfx/signalfx-agent-dev:k8s-test
     - persist_to_workspace:
         root: /tmp/workspace
         paths:
           - final_image.tar

  build_minikube_image:
    <<: *executor
    steps:
      - checkout
      - run: |
          set -x
          docker build -t minikube:latest test-services/minikube
      - run: |
          mkdir -p /tmp/workspace
          docker save -o /tmp/workspace/minikube_image.tar minikube:latest
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - minikube_image.tar

  lint: 
    <<: *executor
    steps:
      - *attach_workspace
      - *import_image
      - run: docker run --rm signalfx-agent-dev make lint

  vet: 
    <<: *executor
    steps:
      - *attach_workspace
      - *import_image
      - run: docker run --rm signalfx-agent-dev make vet

  gotests: 
    <<: *executor
    steps:
      - *attach_workspace
      - *import_image
      - run: |
          set +e
          for ((i=0; i<3; i++)); do
              mkdir ~/testresults
              docker run --rm \
                -v ~/testresults:/output \
                signalfx-agent-dev \
                bash -eo pipefail -c "make templates && go test -v ./... | go2xunit > /output/unit.xml" && exit 0
              rm -rf ~/testresults
              sleep 10
          done
          exit 1

      - store_test_results:
          path: ~/testresults

  docs_test: 
    <<: *executor
    steps:
      - *attach_workspace
      - *import_image
      - checkout
      - run: |
          docker run --rm \
            -v $(eval "echo -n $CIRCLE_WORKING_DIRECTORY")/.git:/go/src/github.com/signalfx/signalfx-agent/.git \
            signalfx-agent-dev \
            bash -ec "make docs && git diff --exit-code" || \
            (echo 'Docs are not updated in the repo! Run `make docs` in the dev image and commit those changes.' && exit 1)

  integration_tests: 
    <<: *executor
    steps:
      - *attach_workspace
      - *import_image
      - run: |
          set +e
          for ((i=0; i<3; i++)); do
              mkdir ~/testresults
              docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/testresults:/output signalfx-agent-dev pytest -n8 --junitxml=/output/integration_tests.xml -m "not packaging and not installer and not k8s" tests && exit 0
              rm -rf ~/testresults
              sleep 10
          done
          exit 1
      - store_test_results:
          path: ~/testresults

  k8s_v1.9.4_integration_tests:
    <<: *executor
    environment:
      K8S_VERSION: "v1.9.4"
    steps:
      - *attach_workspace
      - *import_image
      - *import_final_image
      - *import_minikube_image
      - *run_k8s_integration_tests
      - store_test_results:
          path: ~/testresults
      - store_artifacts:
          path: ~/testresults/k8s_integration_tests.html

  k8s_v1.9.0_integration_tests:
    <<: *executor
    environment:
      K8S_VERSION: "v1.9.0"
    steps:
      - *attach_workspace
      - *import_image
      - *import_final_image
      - *import_minikube_image
      - *run_k8s_integration_tests
      - store_test_results:
          path: ~/testresults
      - store_artifacts:
          path: ~/testresults/k8s_integration_tests.html

  k8s_v1.8.0_integration_tests:
    <<: *executor
    environment:
      K8S_VERSION: "v1.8.0"
    steps:
      - *attach_workspace
      - *import_image
      - *import_final_image
      - *import_minikube_image
      - *run_k8s_integration_tests
      - store_test_results:
          path: ~/testresults
      - store_artifacts:
          path: ~/testresults/k8s_integration_tests.html

  k8s_v1.7.5_integration_tests:
    <<: *executor
    environment:
      K8S_VERSION: "v1.7.5"
    steps:
      - *attach_workspace
      - *import_image
      - *import_final_image
      - *import_minikube_image
      - *run_k8s_integration_tests
      - store_test_results:
          path: ~/testresults
      - store_artifacts:
          path: ~/testresults/k8s_integration_tests.html

  k8s_v1.7.4_integration_tests:
    <<: *executor
    environment:
      K8S_VERSION: "v1.7.4"
    steps:
      - *attach_workspace
      - *import_image
      - *import_final_image
      - *import_minikube_image
      - *run_k8s_integration_tests
      - store_test_results:
          path: ~/testresults
      - store_artifacts:
          path: ~/testresults/k8s_integration_tests.html

  k8s_v1.7.3_integration_tests:
    <<: *executor
    environment:
      K8S_VERSION: "v1.7.3"
    steps:
      - *attach_workspace
      - *import_image
      - *import_final_image
      - *import_minikube_image
      - *run_k8s_integration_tests
      - store_test_results:
          path: ~/testresults
      - store_artifacts:
          path: ~/testresults/k8s_integration_tests.html

  k8s_v1.7.2_integration_tests:
    <<: *executor
    environment:
      K8S_VERSION: "v1.7.2"
    steps:
      - *attach_workspace
      - *import_image
      - *import_final_image
      - *import_minikube_image
      - *run_k8s_integration_tests
      - store_test_results:
          path: ~/testresults
      - store_artifacts:
          path: ~/testresults/k8s_integration_tests.html

  k8s_v1.7.0_integration_tests:
    <<: *executor
    environment:
      K8S_VERSION: "v1.7.0"
    steps:
      - *attach_workspace
      - *import_image
      - *import_final_image
      - *import_minikube_image
      - *run_k8s_integration_tests
      - store_test_results:
          path: ~/testresults
      - store_artifacts:
          path: ~/testresults/k8s_integration_tests.html

  rpm_package_tests:
    <<: *executor
    steps:
      - checkout
      - run: |
          mkdir ~/testresults

          if ! scripts/changes-include-dir packaging/rpm; then
              echo "RPM packaging code has not changed, skipping tests!"
              exit 0
          fi

          sudo apt-get update && sudo apt-get install -y python3-pip
          sudo pip3 install -r tests/requirements.txt

          export PULL_CACHE=yes
          ./packaging/rpm/build

          mkdir /tmp/scratch

          pytest -n auto -m "rpm" --junitxml=~/testresults/rpm.xml ./tests/packaging

      - store_test_results:
          path: ~/testresults

      - store_artifacts:
          path: ~/project/packaging/rpm/output
          destination: /packages/

  deb_package_tests:
    <<: *executor
    steps:
      - checkout
      - run: |
          mkdir ~/testresults

          if ! scripts/changes-include-dir packaging/deb; then
              echo "Debian packaging code has not changed, skipping tests!"
              exit 0
          fi

          sudo apt-get update && sudo apt-get install -y python3-pip
          sudo pip3 install -r tests/requirements.txt

          export PULL_CACHE=yes
          ./packaging/deb/build

          mkdir /tmp/scratch

          pytest -n auto -m "deb" --junitxml=~/testresults/deb.xml ./tests/packaging

      - store_test_results:
          path: ~/testresults

      - store_artifacts:
          path: ~/project/packaging/deb/output
          destination: /packages/

  chef_tests:
    <<: *executor
    steps:
      - checkout
      - run: |
          mkdir ~/testresults

          if ! scripts/changes-include-dir deployments/chef; then
              echo "Chef cookbook code has not changed, skipping tests!"
              exit 0
          fi

          cd deployments/chef
          make dev-image
          docker run --rm \
            signalfx-agent-chef-dev \
            chef exec rspec --format RspecJunitFormatter > ~/testresults/chefspec.xml

          docker run --rm \
            signalfx-agent-chef-dev \
            foodcritic .

      - store_test_results:
          path: ~/testresults

  puppet_tests:
    <<: *executor
    steps:
      - checkout
      - run: |
          mkdir ~/testresults

          if ! scripts/changes-include-dir deployments/puppet; then
              echo "Puppet module code has not changed, skipping tests!"
              exit 0
          fi

          cd deployments/puppet
          make dev-image
          docker run --rm \
            signalfx-agent-puppet-dev \
            rspec spec --format RspecJunitFormatter > ~/testresults/puppetspec.xml

          docker run --rm \
            signalfx-agent-puppet-dev \
            puppet-lint .

      - store_test_results:
          path: ~/testresults

  salt_tests:
    <<: *executor
    steps:
      - checkout
      - run: |
          mkdir ~/testresults

          if ! scripts/changes-include-dir deployments/salt; then
              echo "Salt module code has not changed, skipping tests!"
              exit 0
          fi

          cd deployments/salt
          make dev-image
          docker run --rm \
          signalfx-agent-salt-dev salt '*' state.apply > ~/testresults/salt.out


      - store_test_results:
          path: ~/testresults

  ansible_tests:
    <<: *executor
    steps:
      - checkout
      - run: |
          mkdir ~/testresults

          if ! scripts/changes-include-dir deployments/ansible; then
              echo "Ansible playbook code has not changed, skipping tests!"
              exit 0
          fi

          cd deployments/ansible
          make dev-image
          docker run --rm \
            signalfx-agent-ansible-dev \
            ansible-playbook -i inventory example-playbook.yml --connection=local > ~/testresults/ansible.out

          docker run --rm \
            signalfx-agent-ansible-dev \
            ansible-lint .

      - store_test_results:
          path: ~/testresults

workflows:
  version: 2
  build_test:
    jobs:
     - build
     - build_final_image
     - build_minikube_image
     - lint:
        requires:
         - build
     - vet:
        requires:
         - build
     - gotests:
        requires:
         - build
     - integration_tests:
        requires:
         - build
     - k8s_v1.9.4_integration_tests:
        requires:
         - build
         - build_final_image
         - build_minikube_image
     - k8s_v1.9.0_integration_tests:
        requires:
         - build
         - build_final_image
         - build_minikube_image
     - k8s_v1.8.0_integration_tests:
        requires:
         - build
         - build_final_image
         - build_minikube_image
     - k8s_v1.7.5_integration_tests:
        requires:
         - build
         - build_final_image
         - build_minikube_image
     - k8s_v1.7.4_integration_tests:
        requires:
         - build
         - build_final_image
         - build_minikube_image
     - k8s_v1.7.3_integration_tests:
        requires:
         - build
         - build_final_image
         - build_minikube_image
     - k8s_v1.7.2_integration_tests:
        requires:
         - build
         - build_final_image
         - build_minikube_image
     - k8s_v1.7.0_integration_tests:
        requires:
         - build
         - build_final_image
         - build_minikube_image
     - docs_test:
        requires:
         - build
     - rpm_package_tests
     - deb_package_tests
     - chef_tests
     - puppet_tests
     - salt_tests
     - ansible_tests
