apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
    name: signalfx-agent
    labels:
        version: 2.2.2
        app: signalfx-agent
spec:
  selector:
    matchLabels:
      app: signalfx-agent
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: signalfx-agent
        version: 2.2.2
    spec:
      # Use host network so we can access kubelet directly
      hostNetwork: true
      restartPolicy: Always
      #imagePullSecrets:
      #- name: signalfuse
      tolerations:
      - effect: NoSchedule
        key: node.alpha.kubernetes.io/role
        operator: Exists
      containers:
      - name: signalfx-agent
        image: quay.io/signalfx/signalfx-agent:2.2.2
        command:
        - /bin/signalfx-agent
        - -config
        - /mnt/config/agent.yaml
        volumeMounts:
        - mountPath: /mnt/config
          name: config
        - mountPath: /hostfs
          name: hostfs
          readOnly: true
        env:
        - name: SFX_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: signalfx
              key: access-token
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
      volumes:
      - name: config
        configMap:
          name: signalfx-agent
      - name: hostfs
        hostPath:
          path: /
