apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: apache
  name: apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - image: 906383545488.dkr.ecr.us-west-2.amazonaws.com/apache:2.4.18
        name: apache
