apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: spud
  name: spud
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spud
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spud
    spec:
      containers:
      - image: quay.io/jcamp/spud:latest
        name: spud
        env:
        - name: KUBERNETES_NODE_NAME
          valueFrom:
              fieldRef:
                  fieldPath: spec.nodeName
