apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
    name: mongo
    labels:
        app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: document-store
        ports:
        - containerPort: 27017
